### ISSUE TITLE
Runners unavailable

### ISSUE THREAD

**Issue by cityofships** [stackhpc/stackhpc-kayobe-config#237]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/19818516/202707409-895648c6-0e0f-4ecc-b81b-161bc67ab6b9.png">

**Comment by cityofships** [comment]
![image](https://user-images.githubusercontent.com/19818516/202991144-1bbc081c-ea40-4815-bc7c-40702f8d839b.png)
![image](https://user-images.githubusercontent.com/19818516/202991214-b4096531-73c0-4b38-ada3-9e019657066c.png)

**Comment by markgoddard** [comment]
The runner was shut off. Perhaps a hypervisor reboot? It's now back online

**Comment by cityofships** [comment]
It's better to have a pool of available runners spread across multiple hypervisors in case one of them goes down - issue is back: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/3519321307/jobs/5899152288
